[package]
name = "Uni Freiburg Poster"
version = "0.1.0"
authors = ["Jonas Pleyer<jonas.sci@pleyer.org>"]
license = "MIT"

[template]
path = "."
entrypoint = "pop-uni-fr-poster.typ"
thumbnail = "pop-uni-fr-poster-thumbnail.png"

