baseURL = 'https://jonaspleyer.github.io/science-posters/'
languageCode = 'en-us'
title = 'science-posters'
theme = "hugo-book"

[params]
author = "Jonas Pleyer"
author_mail = "jonas.sci@pleyer.org"
BookSection = '.'

[markup.goldmark.renderer]
unsafe = true

