baseURL = 'https://jonaspleyer.github.io/typst-posters/'
languageCode = 'en-us'
title = 'typst-posters'
theme = "docs"

[params]
author = "Jonas Pleyer"
author_mail = "jonas.sci@pleyer.org"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = "Documentation"
pageRef = '/documentation'
weight = 20

[[menus.main]]
parent = "Documentation"
name = "Boxes"
pageRef = '/documentation/boxes'
weight = 22

[[menus.main]]
parent = "Documentation"
name = "Themes"
pageRef = "/documentation/themes"
weight = 25

[[menus.main]]
name = 'Showcase'
pageRef = '/showcase'
weight = 30

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
