name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: lib.typ

      # build-examples:
      #   runs-on: ubuntu-latest
      #   steps:
      #     - name: Checkout
      #       uses: actions/checkout@v3
      #     - name: Install Typst
      #     - run: 

